### ISSUE TITLE
runSimulations.py does nothing and immediately closes

### ISSUE THREAD

**Issue by Mlvluu** [cRz-Shadows/Pokemon_Trainer_Tournament_Simulator#4]
After having installed the repository properly (I think), setting up the builds and teams, and (probably) successfully using BuildBattles.py (the command prompt yields a number and then disappears), I try to run runSimulations.py, and all it does is open a blank command prompt, stay for less than a second, and close. I don't see any output file. Running findErrors.py yields something about "No module named 'tqdm'".

**Comment by cRz-Shadows** [comment]
No module named 'tqdm' means you haven't installed tqdm, please follow the instructions in [manual.md](https://github.com/cRz-Shadows/Pokemon_Trainer_Tournament_Simulator/blob/main/manual.md)

**Comment by Mlvluu** [comment]
I followed them.
No string in that entire file matches "tqdm". It's not mentioned.

**Comment by cRz-Shadows** [comment]
Ahh it's used in the error file but not the simulations one, but it is in requirements.txt which is mentioned in that file and says to check. I get the sense here you are trying to just double click run files instead of actually running the commands in some terminal. You would be able to see the output if you were.

**Comment by Mlvluu** [comment]
I... would say that installing all the requirements listed in that other file worked, but now it only seems to run battles between the first two teams, and findErrors.py yields this:
![image](https://github.com/cRz-Shadows/Pokemon_Trainer_Tournament_Simulator/assets/36082336/4fedc410-eb00-41c0-93db-6264fb340546)

**Comment by cRz-Shadows** [comment]
The error checking files are meant to find errors in the battles after they have been run, if you are not getting an output those will be useless. I suggest you run buildbattles in the terminal then check if tounament_battles.json was successfully created in Inputs. If not, well there's your problem, if so run runSimulations in the terminal and see what it outputs.

**Comment by Mlvluu** [comment]
Ah, no, I am getting an output now.
Just that it only shows the 100 battles between the first two teams, so I presume those are the only ones being run for some reason.
The command prompt now initially shows the number from the prompt opened by BuildBattles.py, then, after some delay, 100.
Building tournament_battles.json hasn't been a problem so far.

**Comment by cRz-Shadows** [comment]
Oh you have the limiter set in runSimulations. 
```
n = 100 # number of battles to stop running after
teams = teams[:n] # comment this out to simulate all battles
```

**Comment by obaming** [comment]
Same thing is happening to me, I get the "no module named tqdm" error and I have it installed (via pip install tqdm)
