### ISSUE TITLE
A way to enable Dynamax/Tera?

### ISSUE THREAD

**Issue by HMNIJoe** [cRz-Shadows/Pokemon_Trainer_Tournament_Simulator#7]
When running a simulation the trainers have not dynamaxed or terastalized. I've found the section seemingly related to these in simulation-test-1.ts but have been unable to enable them
![Screenshot 2024-06-27](https://github.com/cRz-Shadows/Pokemon_Trainer_Tournament_Simulator/assets/174010414/13275e78-4214-4f74-80fa-c3a69d483bd9)

**Comment by cRz-Shadows** [comment]
In random-player-ai.ts 
![image](https://github.com/cRz-Shadows/Pokemon_Trainer_Tournament_Simulator/assets/77461646/c793a1cf-5c22-4a4f-b852-bd4f026f4865)

And I'm fairly certain you'd need to change the generation to 8 for dynamax to work, and keep it at gen 9 for tera.

**Comment by HMNIJoe** [comment]
I see, thank you you for the help!
