### ISSUE TITLE
Is there a way to make it simulate double battles? 

### ISSUE THREAD

**Issue by tastyOats** [cRz-Shadows/Pokemon_Trainer_Tournament_Simulator#8]
I am planning on simulating some teams that I built to determine how good they go against each other. Would like to ask if its possible to do so! 

Also, would like to ask, what is the AI's logic if terastal is enabled? Does it terastal willy nilly or is there specific circumstances that it calculates for?

**Comment by cRz-Shadows** [comment]
If you want it to do double battles or tera, you'll have to code that yourself currently. Doubles AI is mich more complicated and would require a completely seperate AI.

**Comment by tastyOats** [comment]
> If you want it to do double battles or tera, you'll have to code that yourself currently. Doubles AI is mich more complicated and would require a completely seperate AI.

got it! thank you~ will be closing
